# Generated by Django 3.2.4 on 2021-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LT', 'Laptop'), ('Tb', 'Table'), ('Ho', 'Home'), ('HE', 'High Energy'), ('LE', 'Low Energy'), ('In', 'Incremental'), ('AS', 'Assignment/SS'), ('Ph', 'Phone'), ('Gn', 'General'), ('MD', 'Mom/Dad')], max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='task',
            name='contexts',
            field=models.ManyToManyField(to='api.Context'),
        ),
    ]
