# Generated by Django 3.2.4 on 2021-06-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
